# Site settings
title: BlakeQu Blog
SEOTitle: BlakeQu的博客 | Blake Blog | BlakeQu Blog
header-img: img/home-bg.jpg
email: blakequ@gmail.com
description: "关于Android开发、文字与写作、生活体验 | BlakeQu，H5 & Android Development | 这里是 @BlakeQu 的个人博客，与您一起分享和成长。"
keyword: "BlakeQu, Blake, Blake的博客, BlakeQu Blog, 博客, 个人网站, 互联网, Android开发, 产品, 创业者, 凡米小豆"
url: "http://blakequ.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     blakequ
zhihu_username:     blakequ
github_username:    haodynasty
#twitter_username:  blakequ
#facebook_username:  blakequ



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: blakequ
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: blakequ.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，享受创业，享受生活。人生很精彩，做自己的舞台。"
sidebar-avatar: /img/avatar-blakequ.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "凡米小豆",
        href: "http://fanmicloud.com"
    },{
        title: "廖雪峰的博客",
        href: "http://www.liaoxuefeng.com/"
    },{
    	title: "JakeWharton大神",
    	href: "https://github.com/JakeWharton"
    }
]
